[WIP] Refatoração da captura do BRT para compreender a nova API
RJ-SMTR/maestro pull request #150
Opened 2021-10-05 23:02 UTC by gabriel-milan

### Modificações

* Captura de dados aninhados
* Filtragem de 0 <= (timestamp_captura - timestamp_gps) <= 1 retornando vazia para dados aninhados
* Em caso de resultados vazios, emitir erro para os logs como erro da API

### Requer atenção

* Precisa ver como vai ser o esquema do `publish.sql`, queries para desaninhar e afins

2021-11-19 16:16 UTC, fernandascovino requested changes
@Hellcassius lembrar de mudar para prod quando for subir ;)

abrindo outra discussao aqui: vi que você tirou as informações de tratamento que existiam na `table_config`, acho importante termos documentado isso em algum lugar... como devemos migrar isso para o prefect mais para frente, talvez valha usar como boa prática a documentação direto nas funções: https://docs.prefect.io/core/development/style.html#docstrings

2021-11-19 16:38 UTC, Hellcassius commented on bases/br_rj_riodejaneiro_brt_gps/registros/publish.sql
> +from rj-smtr-dev.br_rj_riodejaneiro_brt_gps_staging.registros as t
@fernandascovino tinha apagado o table_config.yaml para que a tabela fosse recriada, acabei passando por cima do fato de que estava preenchida, concordo que seja bom deixar as informações de tratamento documentadas sim. Nesse caso, adicionamos também os passos de tratamento realizados para a API nova? São diferentes do que acontecia na captura da API antiga

2021-11-19 16:50 UTC, Hellcassius commented on bases/br_rj_riodejaneiro_brt_gps/registros/publish.sql
> +from rj-smtr-dev.br_rj_riodejaneiro_brt_gps_staging.registros as t
Além disso, se o intuito dos campos `published_by` e `treated_by` forem o de estabelecer uma linha de comunicação entre algum usuário dos dados e nós, deveríamos trocar as infos de contato do João? :p

2021-11-23 18:25 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/publish.sql
> +from rj-smtr-dev.br_rj_riodejaneiro_brt_gps_staging.registros as t
Opa, sim! É melhor voltar com as infos no table config incluindo os passos da nova, ainda mais agora que vimos que dá para exportar lá direto do BQ. Pode alterar para o seu contato nesse caso

2021-11-23 20:01 UTC, Hellcassius commented on bases/br_rj_riodejaneiro_brt_gps/registros/publish.sql
> +from rj-smtr-dev.br_rj_riodejaneiro_brt_gps_staging.registros as t
@fernandascovino dá uma olhada agora

2021-11-24 01:45 UTC, fernandascovino approved these changes

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros_historico/table_config.yaml
> +        description: Não sei (???)
```suggestion
        description: N/A
```

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
> +<descrição>
```suggestion
Registros de GPS do BRT do município do Rio de Janeiro a cada 1 minuto.
```

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_config.yaml
> +version: <vA.B> # REQUIRED
```suggestion
version: 1.0 # REQUIRED
```

em tese essa agora é a versao estavel, entao faz sentido entrar como 1.0

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
> +Nome: <nome [você]>
```suggestion
Nome: Caio R. S. dos Santos SMTR-RJ
```

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
> +Código: https://github.com/basedosdados/mais/tree/master/bases/br_rj_riodejaneiro_brt_gps/codeTratado por
```suggestion
Código: https://github.com/rj-smtr/maestro/repositories/capturas/br_rj_riodejaneiro_brt_gps/registros.py```

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
>  -----------
```suggestion

Tratado por
-----------
```

2021-11-24 01:45 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
> +
```suggestion
Nível da Observação (i.e. a granularidade da linha)
-------------------
- timestamp_captura

Colunas identificando linhas unicamente
-------------------
- timestamp_captura
- id_veiculo

Cobertura Temporal
------------------
- 2021

Cobertura Espacial
------------------
- brasil
- RJ
- Rio de Janeiro

Tratamento
----------
Padronizei os nomes das colunas
Adicionei a coluna timestamp_captura, relativa ao minuto em que capturamos a API
Extraí o campo comunicacao (em unix seconds) para timestamp_gps (timestamp)
Estruturei o campo content, contendo toda a resposta da API na sua forma original

Frequencia de Atualização
-------------------------
a cada 1 minuto
```

2021-11-24 01:53 UTC, fernandascovino requested changes

2021-11-24 01:53 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
> +Nome: <nome>
```suggestion
Nome: Caio R. S. dos Santos SMTR-RJ
Código: https://github.com/rj-smtr/maestro/repositories/capturas/br_rj_riodejaneiro_brt_gps/registros.py
Website:
Email: caiorogerio.santos@gmail.com
```

2021-11-24 01:53 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros/table_description.txt
> +Código: https://github.com/rj-smtr/maestro/repositories/capturas/br_rj_riodejaneiro_brt_gps/registros.py```
```suggestion
Código: https://github.com/rj-smtr/maestro/repositories/capturas/br_rj_riodejaneiro_brt_gps/registros.py
```

2021-11-24 01:53 UTC, fernandascovino commented on bases/br_rj_riodejaneiro_brt_gps/registros_historico/table_config.yaml
> +source_bucket_name: rj-smtr-dev
@Hellcassius aqui `source_bucket_name`, `project_id_staging`, `project_id_prod` tem que mudar para `rj-smtr-staging` ne? e também lá no table_config da registros

2021-11-24 02:01 UTC, fernandascovino approved these changes

2021-11-24 02:27 UTC, merged